// Default french ingredients

export default [
    'Angélique',
    'Chou de Savoie',
    "Tilleul d'argent",
    'Kiwi',
    'Allium',
    'Oignon de jardin',
    'Poireau',
    'Ail',
    'Ciboulette',
    'Verveine citronnée',
    'Noix de cajou',
    'Ananas',
    'Dill',
    'Pomme pâtissière',
    'Céleri sauvage',
    'Cacahuète',
    'Burdock',
    'Raifort',
    'Estragon',
    'Mugwort',
    'Asperges',
    'Avoine',
    "Fruit de l'étoile",
    'Noix du Brésil',
    'Betterave commune',
    'Bourrache',
    'Moutarde chinoise',
    'Suédois',
    'Viol',
    'Chou commun',
    'Chou-fleur',
    'Choux de Bruxelles',
    'Chou-rave',
    'Brocoli',
    'Chou chinois',
    'Navet',
    "Pois d'Angole",
    'Thé',
    'Câpres',
    'Poivre',
    'Papaye',
    'Carthame',
    'Carvi',
    'Noix de pécan',
    'Châtaigne',
    'Camomille romaine',
    'Pois chiche',
    'Endive',
    'Chicorée',
    'Cannelle chinoise',
    'Cannelle de Ceylan',
    'Pastèque',
    'Chaux',
    'Lemon',
    'Pummelo',
    'Mandarine (Clémentine, Tangerine)',
    'Orange douce',
    'Café',
    'Café arabica',
    'Café Robusta',
    'Coriandre',
    'Noisette commune',
    'Saffron',
    'Melon',
    'Concombre',
    'Cucurbita',
    'Cumin',
    'Curcuma',
    'Coing',
    'Citronnelle',
    'Globe artichaut',
    'Carotte sauvage',
    'kaki japonais',
    'Cardamome',
    'Corneille noire',
    'Loquat',
    'Salade de roquette (ssp.)',
    'Pomme de cire',
    'Sarrasin commun',
    'Sarrasin de Tartarie',
    'Fig',
    'Fennel',
    'Fraise',
    'Black huckleberry',
    'Fève de soja',
    'Tournesol',
    'Argousier',
    'Orge',
    'Hysope',
    'Anis étoilé',
    'Choux des marais',
    'Patate douce',
    'Noyer noir',
    'Noyer commun',
    'Laitue',
    "Pois d'herbe",
    'Sweet bay',
    'Lentilles',
    'Cresson de jardin',
    'Lovage',
    'Graine de lin',
    "L'origan mexicain",
    'Lichee',
    'Lupin',
    'Pomme',
    'Mangue',
    'Camomille allemande',
    'Mélisse',
    'Mentha',
    'Menthe orange',
    'Cornmint',
    'Menthe verte',
    'Menthe poivrée',
    'Nèfle',
    'Gourde amère',
    'Mulberry',
    'Mûre noire',
    'Noix de muscade',
    'Basilic',
    "L'onagre",
    'Olive',
    'Marjolaine douce',
    'Marjolaine en pot',
    "L'origan commun",
    'Riz',
    'Millet',
    'Coquelicot',
    'Fruit de la passion',
    'Panais',
    'Avocat',
    'Persil',
    'Haricot écarlate',
    'Haricot de Lima',
    'Haricot commun',
    'Date',
    "L'étrangleur noir",
    'Anis',
    'Noix de pin',
    'Poivre (épice)',
    'Pistache',
    'Pois commun',
    'Purslane',
    'Prunus (cerise, prune)',
    'Abricot',
    'Sweet cherry',
    'Sour cherry',
    'Prune européenne',
    'Amande',
    'Pêche',
    'Guava',
    'Grenade',
    'Poire',
    'Radis',
    'Rhubarbe de jardin',
    'Cassis',
    'Groseille',
    'Groseille à maquereau',
    'Cresson de fontaine',
    'Romarin',
    'Rubus (Mûre, Framboise)',
    'Cloudberry',
    'Framboise rouge',
    'Framboise noire',
    'Oseille',
    'Sage commun',
    'Sureau noir',
    "La sarriette d'été",
    "La sarriette d'hiver",
    'Rye',
    'Sésame',
    'Tomate',
    'Tomate cerise',
    'Tomate de jardin',
    'Aubergine',
    'Pomme de terre',
    'Rowanberry',
    'Sorgho',
    'Épinards',
    'Clous de girofle',
    'Tamarin',
    'Pissenlit',
    'Fève de cacao',
    'Thym',
    'Linden',
    'Tilleul à petites feuilles',
    'Fenugrec',
    'Blé tendre',
    'Vaccinium (myrtille, canneberge, myrtille)',
    'Myrtille des bois',
    'Sparkleberry',
    'Myrtille en corymbe',
    'Cranberry américaine',
    'Myrtille',
    'Lingonberry',
    'Vanille',
    'Verveine commune',
    'Fève',
    'Haricot Adzuki',
    'Gram bean',
    'Haricot Mung',
    'Haricot grimpant',
    'Niébé',
    'Raisin muscadine',
    'Raisin commun',
    'Maïs',
    'Ginger',
    'Mûre arctique',
    'Banane',
    'Bayberry',
    "Elliott's blueberry",
    'Myrtille du Canada',
    'Myrtille des marais',
    'Groseille de buffle',
    'Céleri-rave',
    'Tiges de céleri',
    'Ciboulette chinoise',
    'Cranberry européenne',
    'Deerberry',
    'Ginseng',
    'Cascade huckleberry',
    'Myrtille à feuilles ovales',
    'Myrtille à feuilles persistantes',
    'Myrtille rouge',
    'Longan',
    'Noix de macadamia (M. tetraphylla)',
    'Oignon de jardin',
    "Raisin d'été",
    'Raisin renard',
    'Nectarine',
    'Pêche',
    'Poivre (C. baccatum)',
    'Poivre (C. chinense)',
    'Poivre (Capsicum)',
    'Rambutan',
    'Riz rouge',
    'Riz sauvage annuel',
    'Bette à carde',
    'Thym citronné',
    'Chou Tronchuda',
    'Noyer japonais',
    'Oignon gallois',
    'Blé dur',
    'Shallot',
    'Salade de roquette',
    'Carotte',
    'Triticale',
    'Chou noir',
    'Myrtille en demi-hauteur',
    'Feuilles de céleri',
    'Feuilles de chicorée',
    'Komatsuna',
    'Pak choy',
    'Chou de Napa',
    'Racines de chicorée',
    'Hybride pamplemousse/pommeau',
    'Pamplemousse',
    'Jostaberry',
    'Kai-lan',
    "L'origan italien",
    'Chou de bœuf',
    'Radis blanc',
    'Radis noir',
    'Radis',
    'Betterave rouge',
    'Sweet rowanberry',
    "Sauge d'ananas",
    'Skunk currant',
    'Bière',
    'Autre pain',
    'Céréales pour le petit déjeuner',
    'Autre produit à base de soja',
    'Autre produit céréalier',
    'Pâtes',
    'Biscuit',
    'Sourdough',
    'Esprit',
    'Vin fortifié',
    'Autres boissons alcoolisées',
    'Abalone',
    'Abiyuch',
    'Acérola',
    'Gland',
    "Courge d'hiver",
    'Agar',
    'Red king crab',
    'Luzerne',
    'Allspice',
    'Amarante',
    'Arrowhead',
    'Arrowroot',
    "Poire d'Asie",
    "Hareng de l'Atlantique",
    "Maquereau de l'Atlantique",
    'Painted comber',
    "La goberge de l'Atlantique",
    'Loup atlantique',
    'Les pousses de bambou',
    'Bar rayé',
    'Noix de hêtre',
    'Baleine béluga',
    'Bison',
    "Poisson noir d'Alaska",
    'Crabe bleu',
    'Moule bleue',
    'Thon rouge du Nord',
    'Bluefish',
    'Sanglier',
    'Baleine boréale',
    "Fruit de l'arbre à pain",
    'Graine de noyer à pain',
    'Rapini',
    'Buffalo',
    'Burbot',
    'Brûlure de beurre géante',
    'Poisson-beurre américain',
    'Butternut',
    'Courge musquée',
    'Calabash',
    'Cardoon',
    'Prune du Natal',
    'Caroube',
    'Carpe commune',
    'Cassave',
    'Poisson-chat de la Manche',
    'Chayote',
    'Cherimoya',
    'Cerfeuil',
    'Chia',
    'Poulet',
    'Brocoli chinois',
    'Châtaigne chinoise',
    "Châtaigne d'eau chinoise",
    'Guirlande de chrysanthèmes',
    'Cisco',
    'Nuttall cockle',
    'Noix de coco',
    'Morue du Pacifique',
    "Morue de l'Atlantique",
    'Poulpe commun',
    'Salade de maïs',
    'Graine de coton',
    'Catjang pea',
    'Malus (pomme de crabe)',
    'Squashberry',
    'Atlantic croaker',
    'Cusk',
    'Seiche',
    'Cerf mulet',
    'Devilfish',
    'Dock',
    'Poisson-dauphin',
    "Tambour d'eau douce",
    'Canard colvert',
    'Crabe dormeur',
    'Durian',
    "Huître de l'Est",
    "Anguille d'eau douce",
    'Sureau',
    'Elk',
    'Emu',
    'Oregon yampah',
    "L'anchois européen",
    'Châtaigne européenne',
    'Turbot',
    'Épilobe',
    'Florida pompano',
    'Ginkgo nuts',
    'Oie grise',
    'Raisin',
    'Flétan du Groenland/turbot',
    'Groundcherry',
    'Grouper',
    'Poule de Guinée',
    'Haddock',
    'Hippoglossus (flétan commun)',
    'Noisette',
    'Noix de caryer',
    'Cheval',
    'Arbre à raifort',
    "Myrtille d'Alaska",
    'Fève de jacinthe',
    "Mousse d'Irlande",
    'Maquereau du Pacifique',
    'Jackfruit',
    'Châtaigne japonaise',
    'Prune de Java',
    'Topinambour',
    'Jujube',
    'Jute',
    'Kale',
    'Kelp',
    'Maquereau royal',
    'Kumquat',
    "Quartier d'agneau",
    'Chiton en cuir',
    'Poireau sauvage',
    'Lingue commune',
    'Lingcod',
    'Homard américain',
    'Loganberry',
    'Lotus',
    'Lotus sacré',
    'Lupin blanc',
    'Epinards Malabar',
    'Pomme de Mammee',
    'Mangoustan violet',
    'Alpine sweetvetch',
    'Milkfish',
    'Baudroie',
    'Fève-mite',
    'Yam de montagne',
    'Mulet rayé',
    'Moutarde blanche',
    'Moutarde et épinards',
    'Epinards de Nouvelle-Zélande',
    'Nopal',
    "La moue de l'océan",
    'Pieuvre géante du Pacifique Nord',
    'Ohelo berry',
    'Okra',
    'Tunicate',
    'Autruche',
    'Spotted seal',
    'Hareng du Pacifique',
    'Huître du Pacifique',
    'Sébaste du Pacifique',
    'Canard en velours',
    'Poivre (C. frutescens)',
    'kaki commun',
    'Faisan',
    'Brochet du Nord',
    'Noix de pili',
    'Colorado pinyon',
    'Pitanga',
    'Le figuier de Barbarie des plaines',
    'Plantain français',
    'American pokeweed',
    'Pavot à opium',
    'Navet de prairie',
    'Figue de Barbarie',
    'Quinoa',
    'Lapin européen',
    'Éperlan arc-en-ciel',
    'Truite arc-en-ciel',
    'Prune Malabar',
    'Rose musquée',
    'Roselle',
    'Hoplostète orange',
    'Morue charbonnière',
    'Saumon rose',
    'Saumon kéta',
    'Saumon coho',
    'Saumon rouge',
    'Saumon quinnat',
    "Saumon de l'Atlantique",
    'Salmonberry',
    'Salsifis commun',
    'Sapodilla',
    'Mamey sapote',
    'Maquereau espagnol',
    'Sardine du Pacifique',
    'Pétoncle',
    'Scup',
    'Concombre de mer',
    "L'otarie de Steller",
    'Sceau barbu',
    'Sceau annelé',
    'Truite de mer',
    'Fleur de Sesbania',
    'American shad',
    'Requin',
    'Sheefish',
    'Mouton (Mutton, Lamb)',
    'Sheepshead',
    'Moutarde de haie',
    'Thon listao',
    'Snapper',
    'Soursop',
    'Épeautre',
    'Spiruline',
    'Squab',
    'Goyave à la fraise',
    'Grand esturgeon',
    'White sucker',
    'Pomme de sucre',
    'Crapet-soleil',
    'Espadon',
    'Taro',
    'Teff',
    'Tilefish',
    'La grenaille mexicaine',
    'Courge de serviettes',
    'Salmonidés (saumon, truite)',
    'Turquie',
    'Bovins (bœuf, veau)',
    'Walleye',
    "Pollock d'Alaska",
    'Wasabi',
    'Gourge cireuse',
    'Whelk',
    'Lieu noir',
    'Grand corégone',
    'Poisson blanc',
    'Merlan',
    'Riz sauvage',
    'Feuille de saule',
    'Haricot ailé',
    'Yam',
    'Jicama',
    'Yautia',
    'Thon à nageoires jaunes',
    'Sériole à queue jaune',
    'Pollock',
    'Thon blanc',
    'Gadus (cabillaud commun)',
    "Flétan de l'Atlantique",
    'Flétan du Pacifique',
    'Saumon du Pacifique',
    'Éperlan',
    'Clupeinae (hareng, sardine, sprat)',
    'Langouste',
    'Crabe des neiges',
    'Pois aux yeux noirs',
    'Chevreuil',
    'Noix de macadamia',
    'Percoidei (Bass et autres)',
    'Perciformes',
    'Lapin',
    'Chèvre domestique',
    'Beefalo',
    'Bivalvia (palourde, moule, huître)',
    'Calamar',
    'Crevettes',
    'Ecrevisse',
    'Poissons plats',
    'Porc domestique',
    'Walrus',
    "Rhubarbe sauvage d'Alaska",
    'Blé oriental',
    'Haricot Yardlong',
    'Caille',
    'Boysenberry',
    'Chaux persane',
    'Feijoa',
    'Rowal',
    "L'oreille du juif",
    'Champignon commun',
    'Shiitake',
    'Lave-vaisselle',
    'Wakame',
    'Enokitake',
    'Epazote',
    'Pleurotes',
    "Mycose de l'oreille nuageuse",
    'Maitake',
    "Fougère d'autruche",
    'Spot croaker',
    'Sourdock',
    'Tinda',
    'Atlantic menhaden',
    'Blé',
    'Cerisier de Virginie commun',
    'Agave',
    'Quenouille à feuilles étroites',
    'Méduse',
    'Anchois',
    'Merlan bleu',
    'Brème de carpe',
    'Chanterelle',
    'Esturgeon',
    'Charr',
    'Cannelle',
    'Crabe',
    'Common dab',
    'Aiguillat commun',
    'Anatidae',
    'Anguilliformes',
    'Vraie grenouille',
    'Garfish',
    'Gadiformes',
    'Lièvre de montagne',
    'Truite de lac',
    'Limande sole',
    'Langouste à pinces',
    'Lumpsucker',
    'Scombridae (bonite, maquereau, thon)',
    'Moule marine',
    'Aiglefin de Norvège',
    'Homard de Norvège',
    'La moue de Norvège',
    'Palmier à huile',
    'Vraie huître',
    'Sago palm',
    'Persimmon',
    'Brochet',
    'Pleuronectidae (limande, flétan, plie)',
    'Rock ptarmigan',
    "Perche de l'océan Pacifique",
    'Salsifis noir',
    'Vrai sceau',
    'Algues rouges',
    'Kombu',
    'Escargot',
    'Vraie sole',
    'Catfish',
    'Chardon',
    'Thunnus',
    'Noyer',
    'Cetacea (dauphin, marsouin, baleine)',
    'Columbidae (Colombe, Pigeon)',
    'Conque',
    'Vin de raisin',
    'Vin de baies',
    'Autre vin',
    'Cidre de pomme',
    "L'alcool",
    'Fromage',
    'Lait (Vache)',
    'Oeufs',
    'Yogourt',
    'Haricot',
    'Vodka',
    'Whisky',
    'Glaces',
    'Gin',
    'Chérie',
    'Réglisse',
    'Vinaigre',
    'Rhum',
    'Vin de Porto',
    'Vermouth',
    'Sherry',
    'Vin de Madère',
    'Nougat',
    'Caramel',
    'Gâteau',
    'Pizza',
    'Ymer',
    'Autres snacks',
    'Pain croustillant',
    'Pâtisserie',
    'Dragée',
    'Chewing-gum',
    'Massepain',
    'Sauce salade',
    'Sauce',
    'Sel',
    'Beurre',
    'Substitut de beurre',
    'Crème',
    'Sucre',
    'Saucisse',
    'Meatball',
    'Moutarde',
    'Pâté',
    'Substitut de sucre',
    'Bouillon de viande',
    'Whey',
    'Caséine',
    'Confiture de fruits',
    'Agent levant',
    'Marshmallow',
    'Gélatine',
    'Eau',
    'Autres produits de la pêche',
    'Lait (humain)',
    'Autre boisson',
    'Aliments pour bébés',
    'Boulette',
    'Soupe',
    'Autre produit végétal',
    'Nourriture ou boisson non classée',
    'Sirop',
    'Suif',
    'Rémoulade',
    'Pâte à tartiner au chocolat',
    'Gomme aux fruits',
    'Poudre de curry',
    'Autres bonbons',
    'Meringue',
    'Lard',
    'Autres graisses animales',
    'Autre produit de cacao',
    'Beurre de cacao',
    'Cacao en poudre',
    'Liqueur de cacao',
    'Chocolat',
    'Chocolat chaud',
    'Lait sec',
    'Lait (autres mammifères)',
    'Kefir',
    'Le babeurre',
    'Autres laits fermentés',
    'Sauce soja',
    'Miso',
    'Tofu',
    'Zwieback',
    'Roe',
    'Cichlidae (Tilapia)',
    'Glaçage',
    'Snack-bar',
    'Tortue verte',
    'Boisson énergétique',
    'Burrito',
    'Hamburger',
    'Haricots cuits',
    'Chili',
    'Taco',
    'Tortilla',
    'Nachos',
    'Fromage fondu',
    'Salade',
    'Substitut de crème',
    'Dulce de leche',
    'Topping',
    'Crème anglaise',
    'Oeuf roulé',
    'Cœur de palmier',
    'Popcorn',
    'Chips',
    'Chips de tortilla',
    'Corn chip',
    "Thé à l'hibiscus",
    'Ragoût',
    'Dessert à la gélatine',
    'Junket',
    'Falafel',
    'Frybread',
    'Autre dessert glacé',
    'Lasagnes',
    'Morchella (Morel)',
    'Pancake',
    'Pectine',
    'Pudding',
    'Waffle',
    'Lait de soja',
    'Pain de viande',
    'Sake',
    'Cocktail',
    'Couscous',
    'Bulgur',
    'Substitut de café',
    'Café moka',
    'Chimichanga',
    'Semoule',
    'Perle de tapioca',
    'Tostada',
    'Quesadilla',
    'Pomme de terre au four',
    'Hot dog',
    'Diffuser',
    'Enchilada',
    "Substitut d'œuf",
    'Boisson nutritive',
    'Autre sandwich',
    'Ketchup',
    'Sandwich de petit déjeuner',
    'Adobo',
    'Macaroni au fromage',
    'Graisse de beurre',
    'Melon cornu',
    'Hushpuppy',
    'Jus de fruits',
    'Relish',
    'Autre produit à base de fruits',
    'Salade de fruits',
    'Yogourt au soja',
    'Alimentation végétarienne',
    'Veggie burger',
    'Cold cut',
    'Noix mélangées',
    'Canola',
    'Paume de Babassu',
    'Cupuaçu',
    'Karité',
    'Camélia oléagineux',
    'Ucuhuba',
    'Pâte phyllo',
    'Huile de cuisson',
    'Croûte de tarte',
    'Garniture de tarte',
    'Pie',
    'Raccourcissement',
    'Crème de soja',
    'Cornet de glace',
    'Mélasse',
    'Cracker',
    'Nance',
    'Naranjilla',
    'Natto',
    'Ravioli',
    'Scrapple',
    'Autre plat de pâtes',
    'Succotash',
    'Tamale',
    'Gâteau de riz',
    'Fougère arborescente',
    'Lait évaporé',
    'Farine',
    'Akutaq',
    'Pâte',
    'Pain pita',
    'Focaccia',
    'Bagel',
    'Autre produit de boulangerie',
    'Pain piki',
    'Pain perdu',
    'Pain de blé',
    'Pain de seigle',
    "Pain d'avoine",
    'Pain de pommes de terre',
    'Cornbread',
    'Corn grits',
    'Pain multigrains',
    'Pain de riz',
    'Pan dulce',
    'Pain aux raisins',
    'Wonton wrapper',
    'Trail mix',
    'Thé Greenthread',
    'Boisson à saveur de fruits',
    'Jus de légumes',
    'Horchata',
    'Boisson non alcoolisée',
    'Yaourt glacé',
    'Milkshake',
    'Mousse au chocolat',
    'Goutte',
    'Pupusa',
    'Empanada',
    'Arepa',
    'Ascidiens',
    'Gefilte fish',
    'Lys jaune',
    'Fish burger',
    'Autre plat',
    'Tarte à la marmite',
    'Farce',
    'Coquille comestible',
    'Fudge',
    'Barre de chocolat',
    'Lait condensé',
    'Margarine',
    'Pâte à tartiner de type margarine',
    'Hummus',
    'Feuilletés aux pommes de terre',
    'Gratin de pommes de terre',
    'Substitut de lait',
    'Poivre (C. pubescens)',
    'Ail à collier',
    'Chou',
    'Laurier chinois',
    'Champignons',
    'Boissons alcoolisées',
    'Légumes de la famille des oignons',
    'Pomes',
    'Brassicas',
    'Céréales et produits céréaliers',
    'Citrus',
    'Cacao et produits de cacao',
    'Café et produits à base de café',
    'Crustacés',
    'Lait et produits laitiers',
    'Graisses et huiles',
    'Poissons',
    'Herbes et épices',
    'Pulses',
    'Mollusques',
    'Noix',
    'Boissons',
    'Fruits',
    'Légumes verts',
    'Légumes-racines',
    'Courges ensoleillées (pattypan squash)',
    'Courgettes vertes',
    'Courgettes jaunes',
    'Poivron vert',
    'Poivron jaune',
    'Poivron orange',
    'Poivron rouge',
    'Poivron rouge italien',
    'Haricot de cire jaune',
    'Haricot vert',
    'Amélanche',
    'Nankin cerise',
    'Citrouille japonaise',
    'Chou blanc',
    'Laitue romaine',
    'Lait de vache, pasteurisé, vitamines A + D ajoutées, 0% de matières grasses',
    'Lait de vache, pasteurisé, vitamines A + D ajoutées, 1% de matières grasses',
    'Lait de vache, pasteurisé, vitamines A + D ajoutées, 2% de matières grasses',
    'Lait de vache, pasteurisé, additionné de vitamine D, 3,25% de matières grasses',
    'Castanospermum australe',
    'Gentiana lutea',
    'Juniperus communis',
    'Albizia gummifera',
    'Mundu',
    'Rabbiteye blueberry',
    'Poire de Yali',
    'Asparagus racemosus',
    'Mûre à feuilles persistantes',
    'Fougère asperge',
    'Mûre sans épines',
    'Mûre des hauts plateaux tropicaux',
    'Mûre des Andes',
    'Blackberry',
    'Thé noir',
    'Thé vert',
    "Huile d'olive",
    'Macroalgues',
    'Vin rouge',
    'huile de lin',
    'Huile de colza',
    'Huile de soja',
    'Guarana',
    'Mate',
    'Vin blanc',
    'Orange aigre',
    "Jaune d'œuf",
    'Vin rosé',
    'Mûre blanche',
    'Huile de canola',
    'Vin de dessert',
    'Champagne rouge',
    'Thé rouge',
    'Champagne blanc',
    'Jus de raisin rouge',
    'Jus de raisin blanc',
    'Crosne',
    'Trèfle rouge',
    'Baies de perdrix',
    'Mikan',
    'Fromage mozzarella',
    'Fromage à la crème nature',
    'Fromage Cheddar',
    'Fromage parmesan',
    "Lait d'amande",
    'Lait de coco',
    'Beurre salé',
    'Huile de tournesol',
    'Huile de noix de coco',
    "Huile d'arachide",
    'Huile de coton',
    'Huile de maïs',
    "Huile d'avocat",
    'Huile de pépins de raisin',
    'Huile de sésame',
    'Fromage Monterey Jack',
    'Fromage suisse',
    'Fromage blanc',
    'Fromage bleu',
    'Clam',
    'Crème aigre',
    'Pain de blé entier',
    'Piment jalapeno',
    'La feta grecque',
    'Eddoe',
    'Plantain',
    'Clémentine',
    'Pomme verte',
    'Oignon blanc',
    'Oignon rouge',
    'Oignon vert',
    'Raisin vert',
    'Raisin rouge',
    'Prune noire',
    'Chou vert',
    'Raisin noir',
    'Haricot Cannellini',
    'Lentille verte',
    'Poivre de Cubanelle',
    'Courges à gland',
    'Laitue Iceberg',
    'Bar de mer japonais',
    'Pea shoots',
    'Yau choy',
    "Eau d'épinards",
    'Prune chinoise',
    'Prune verte',
    'Wampee',
    'Pitaya',
    'Goji',
    'Fruit du moine',
    'Melon cantaloup',
    'Aubépine',
    'Fruits de lanterne',
    'Pain blanc',
    'Cape gooseberry',
    'Tisane',
    'Huile de poisson',
    'Coquille de taco',
    'Coquille de Tostada',
];
